# Copyright 2026 Vijaykumar Singh <vijay@anvaiops.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.

"""The dependency-automation exception must not weaken attribution policy."""

import importlib.util
from pathlib import Path

import pytest

_PATH = Path(__file__).resolve().parents[3] / "scripts/ci/check_no_agent_attribution.py"
_SPEC = importlib.util.spec_from_file_location("attribution_guard", _PATH)
assert _SPEC and _SPEC.loader
_GUARD = importlib.util.module_from_spec(_SPEC)
_SPEC.loader.exec_module(_GUARD)
_OFFICIAL = "Co-authored-by: dependabot[bot] " "<49699333+dependabot[bot]@users.noreply.github.com>"


@pytest.mark.parametrize("trailer", [_OFFICIAL, _OFFICIAL.upper(), "\t" + _OFFICIAL + "  "])
def test_official_dependency_automation_is_allowed(trailer):
    assert _GUARD.scan("chore(deps): update package\n\n" + trailer, "test") == []


@pytest.mark.parametrize(
    "text",
    [
        _OFFICIAL.replace("49699333", "12345678"),
        _OFFICIAL.replace("users.noreply.github.com", "evil.com"),
        "Co-authored-by: dependabot[bot] <dependabot[bot]@evil.com>",
        _OFFICIAL + " unrelated suffix",
        _OFFICIAL + " Generated by Claude",
        _OFFICIAL.replace("dependabot[bot]", "copilot[bot]"),
        "Generated-by: dependabot[bot]",
        "Co-authored-by: unknown[bot] <unknown@example.com>",
        "Co-authored-by: Codex <noreply@openai.com>",
        "Assisted-by: Claude",
        _OFFICIAL + "\nCo-authored-by: Claude <noreply@anthropic.com>",
    ],
)
def test_lookalikes_suffixes_and_other_agents_are_still_blocked(text):
    assert _GUARD.scan(text, "test")


def test_existing_first_party_and_technical_mentions_remain_allowed():
    assert (
        _GUARD.scan("Document OpenAI APIs and CLAUDE.md\nGenerated-by: victor-code-ai", "test")
        == []
    )
